//paper
export const NO_PAPER = 'no_paper',
  OFFSET_80 = 'offset_80',
  COATED_120 = 'coated_120',
  COATED_160 = 'coated_160',
  COATED_300 = 'coated_300',
  UNCOATED_150 = 'uncoated_150',
  UNCOATED_170 = 'uncoated_170',
  UNCOATED_200 = 'uncoated_200',
  UNCOATED_250 = 'uncoated_250',
  UNCOATED_300 = 'uncoated_300',
  //printing
  NO_PRINT = 'no_print',
  ONE_SIDED_GRAYSCALE = 'one_sided_grayscale',
  TWO_SIDED_GRAYSCALE = 'two_sided_grayscale',
  ONE_SIDED_COLOR = 'one_sided_color',
  TWO_SIDED_COLOR = 'two_sided_color',
  //laminations
  NO_LAMIN = 'no_lamin',
  ONE_SIDED_MATTE = 'one_sided_matte',
  TWO_SIDED_MATTE = 'two_sided_matte',
  ONE_SIDED_GLOSSY = 'one_sided_glossy',
  TWO_SIDED_GLOSSY = 'two_sided_glossy',
  //binding types
  STAPLES = 'staples',
  METAL_SPRING = 'metal_spring',
  PLASTIC_SPRING = 'plastic_spring',
  THERMOBINDER = 'thermobinder',
  FOLDER = 'folder',
  CANAL = 'canal',
  RING = 'ring',
  //formats
  A3 = 'A3',
  A4 = 'A4',
  A5 = 'A5',
  A6 = 'A6',
  //orientations
  PORTRAIT = 'portrait',
  LANDSCAPE = 'landscape',
  //count coefs
  LAMIN = 'lamin',
  TRIM = 'trim',
  //format coefs
  PRINTED_COEF = 'printed_coef',
  BIND_COEF = 'bind_coef',
  //Form Calculator
  SELECT = 'select',
  INPUT_RADIO = 'radio_input',
  INPUT_NUMBER = 'number_input',
  MAIN_PAGE = 'main_page',
  SERVICES_PAGE = 'services_page',
  PRODUCTS_PAGE = 'products_page',
  SPECIAL_PAGE = 'special_page',
  CONTACTS_PAGE = 'contacts_page',
  TRACK_ORDER_PAGE = 'track_order_page',
  UK = 'uk',
  RU = 'ru';
