export const builder = [
  {
    productName: 'DRAWS',
    serviceName: 'STAPLES',
    href: '/services/staples',
    img: 'staples.webp',
    alt: '',
    advantages: ['STAPLES_ADV_1', 'STAPLES_ADV_2', 'STAPLES_ADV_3'],
  },
  {
    productName: 'BOOK',
    serviceName: 'HARD_COVER',
    href: '/services/hard-cover',
    img: 'hard-cover.webp',
    alt: '',
    advantages: ['HARD_COVER_ADV_1', 'HARD_COVER_ADV_2', 'HARD_COVER_ADV_3'],
  },
  {
    productName: 'NOTEPAD',
    serviceName: 'METAL_SPRING',
    href: '/services/metal-spring',
    img: 'metal.webp',
    alt: '',
    advantages: [
      'METAL_SPRING_ADV_1',
      'METAL_SPRING_ADV_2',
      'METAL_SPRING_ADV_3',
    ],
  },
  {
    productName: 'BOOK',
    serviceName: 'THERMOBINDER',
    href: '/services/thermobinder',
    img: 'thermobinder.webp',
    alt: '',
    advantages: [
      'THERMOBINDER_ADV_1',
      'THERMOBINDER_ADV_2',
      'THERMOBINDER_ADV_3',
    ],
  },
  {
    productName: 'DRAWS',
    serviceName: 'PLASTIC_SPRING',
    href: '/services/plastic-spring',
    img: 'plastic.webp',
    alt: '',
    advantages: [
      'PLASTIC_SPRING_ADV_1',
      'PLASTIC_SPRING_ADV_2',
      'PLASTIC_SPRING_ADV_3',
    ],
  },
  {
    productName: 'DIPLOMA',
    serviceName: 'CANAL',
    href: '/services/canal',
    img: 'canal.webp',
    alt: '',
    advantages: ['CANAL_ADV_1', 'CANAL_ADV_2', 'CANAL_ADV_3'],
  },
  {
    productName: 'CATALOG',
    serviceName: 'RING',
    href: '/services/ring',
    img: 'ring.webp',
    alt: '',
    advantages: ['RING_ADV_1', 'RING_ADV_2', 'RING_ADV_3'],
  },
  {
    productName: 'DOCUMENTS',
    serviceName: 'FOLDER',
    href: '/services/folder',
    img: 'folder.webp',
    alt: '',
    advantages: ['FOLDER_ADV_1', 'FOLDER_ADV_2', 'FOLDER_ADV_3'],
  },
];
