export const builder = [
  {
    productname: 'draws',
    servicename: 'staples',
    href: '/services/staples',
    img: 'staples.webp',
    alt: '',
    advantages: [
      'staples_adv_1',
      'staples_adv_2',
      'staples_adv_3',
    ],
  },
  {
    productname: 'book',
    servicename: 'hard_cover',
    href: '/services/hard-cover',
    img: 'hard-cover.webp',
    alt: '',
    advantages: [
      'hard_cover_adv_1',
      'hard_cover_adv_2',
      'hard_cover_adv_3',
    ],
  },
  {
    productname: 'notepad',
    servicename: 'metal_spring',
    href: '/services/metal-spring',
    img: 'metal.webp',
    alt: '',
    advantages: [
      'metal_spring_adv_1',
      'metal_spring_adv_2',
      'metal_spring_adv_3',
    ],
  },
  {
    productname: 'book',
    servicename: 'thermobinder',
    href: '/services/thermobinder',
    img: 'thermobinder.webp',
    alt: '',
    advantages: [
      'thermobinder_adv_1',
      'thermobinder_adv_2',
      'thermobinder_adv_3',
    ],
  },
  {
    productname: 'draws',
    servicename: 'plastic_spring',
    href: '/services/plastic-spring',
    img: 'plastic.webp',
    alt: '',
    advantages: [
      'plastic_spring_adv_1',
      'plastic_spring_adv_2',
      'plastic_spring_adv_3',
    ],
  },
  {
    productname: 'diploma',
    servicename: 'canal',
    href: '/services/canal',
    img: 'canal.webp',
    alt: '',
    advantages: [
      'canal_adv_1',
      'canal_adv_2',
      'canal_adv_3',
    ],
  },
  {
    productname: 'catalog',
    servicename: 'ring',
    href: '/services/ring',
    img: 'ring.webp',
    alt: '',
    advantages: [
      'ring_adv_1',
      'ring_adv_2',
      'ring_adv_3',
    ],
  },
  {
    productname: 'documents',
    servicename: 'folder',
    href: '/services/folder',
    img: 'folder.webp',
    alt: '',
    advantages: [
      'folder_adv_1',
      'folder_adv_2',
      'folder_adv_3',
    ],
  },
];
