export const builder = {
  services: [
    {
      productName: 'draws',
      serviceName: 'staples',
      href: '/services/staples',
      img: 'staples.webp',
      alt: '',
      advantages: ['staples_adv_1', 'staples_adv_2', 'staples_adv_3'],
    },
    {
      productName: 'book',
      serviceName: 'hard_cover',
      href: '/services/hard-cover',
      img: 'hard-cover.webp',
      alt: '',
      advantages: ['hard_cover_adv_1', 'hard_cover_adv_2', 'hard_cover_adv_3'],
    },
    {
      productName: 'notepad',
      serviceName: 'metal_spring',
      href: '/services/metal-spring',
      img: 'metal.webp',
      alt: '',
      advantages: [
        'metal_spring_adv_1',
        'metal_spring_adv_2',
        'metal_spring_adv_3',
      ],
    },
    {
      productName: 'book',
      serviceName: 'thermobinder',
      href: '/services/thermobinder',
      img: 'thermobinder.webp',
      alt: '',
      advantages: [
        'thermobinder_adv_1',
        'thermobinder_adv_2',
        'thermobinder_adv_3',
      ],
    },
    {
      productName: 'draws',
      serviceName: 'plastic_spring',
      href: '/services/plastic-spring',
      img: 'plastic.webp',
      alt: '',
      advantages: [
        'plastic_spring_adv_1',
        'plastic_spring_adv_2',
        'plastic_spring_adv_3',
      ],
    },
    {
      productName: 'diploma',
      serviceName: 'canal',
      href: '/services/canal',
      img: 'canal.webp',
      alt: '',
      advantages: ['canal_adv_1', 'canal_adv_2', 'canal_adv_3'],
    },
    {
      productName: 'catalog',
      serviceName: 'ring',
      href: '/services/ring',
      img: 'ring.webp',
      alt: '',
      advantages: ['ring_adv_1', 'ring_adv_2', 'ring_adv_3'],
    },
    {
      productName: 'documents',
      serviceName: 'folder',
      href: '/services/folder',
      img: 'folder.webp',
      alt: '',
      advantages: ['folder_adv_1', 'folder_adv_2', 'folder_adv_3'],
    },
  ],
  products: [
    {
      productName: 'production of',
      serviceName: 'notebooks',
      href: '/products/notebooks',
      img: 'metal.webp',
      alt: '',
      advantages: ['notebooks_adv_1', 'notebooks_adv_2', 'notebooks_adv_3'],
    },
    {
      productName: 'production of',
      serviceName: 'catalogs',
      href: '/products/catalogs',
      img: 'staples.webp',
      alt: '',
      advantages: ['hard_cover_adv_1', 'hard_cover_adv_2', 'hard_cover_adv_3'],
    },
    {
      productName: 'synopsis',
      serviceName: 'printing',
      href: '/products/synopsis',
      img: 'synopsis.webp',
      alt: '',
      advantages: [
        'metal_spring_adv_1',
        'metal_spring_adv_2',
        'metal_spring_adv_3',
      ],
    },
    {
      productName: 'book',
      serviceName: 'printing',
      href: '/products/books',
      img: 'book.webp',
      alt: '',
      advantages: [
        'thermobinder_adv_1',
        'thermobinder_adv_2',
        'thermobinder_adv_3',
      ],
    },
    {
      productName: 'calendar',
      serviceName: 'printing',
      href: '/products/calendars',
      img: 'calendar.webp',
      alt: '',
      advantages: [
        'plastic_spring_adv_1',
        'plastic_spring_adv_2',
        'plastic_spring_adv_3',
      ],
    },
    {
      productName: 'Brochure of',
      serviceName: 'diplomas/dissertations',
      href: '/products/diplomas',
      img: 'canal.webp',
      alt: '',
      advantages: ['canal_adv_1', 'canal_adv_2', 'canal_adv_3'],
    },
    {
      productName: 'presentation',
      serviceName: 'printing',
      href: '/products/presentations',
      img: 'presentations.webp',
      alt: '',
      advantages: ['ring_adv_1', 'ring_adv_2', 'ring_adv_3'],
    },
    {
      productName: 'stitching',
      serviceName: 'drawings',
      href: '/products/drawings',
      img: 'plastic.webp',
      alt: '',
      advantages: ['folder_adv_1', 'folder_adv_2', 'folder_adv_3'],
    },
  ],
};
