export const MAIN_PAGE = 'MAIN_PAGE',
SERVICES_PAGE = 'SERVICES_PAGE',
PRODUCTS_PAGE = 'PRODUCTS_PAGE',
SPECIAL_PAGE = 'SPECIAL_PAGE',
CONTACTS_PAGE = 'CONTACTS_PAGE',
TRACK_ORDER_PAGE = 'TRACK_ORDER_PAGE',
UK = 'UK',
RU = 'RU'